apiVersion: apps/v1
kind: Deployment
metadata:
  name: hanlon-deployment
  labels:
    app: hanlon-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      group: hanlon
  template:
    metadata:
      labels:
        group: hanlon
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: Exists
      containers:
        - name: ch
          image: clickhouse
          ports:
            - containerPort: 8123
          env:
            - name: CLICKHOUSE_USER
              value: "k3stestuser"
            - name: CLICKHOUSE_PASSWORD
              value: "k3stestuser"
          volumeMounts:
            - mountPath: /var/lib/clickhouse
              name: ch-data
            - mountPath: /var/log/clickhouse-server
              name: ch-server-logs

        - name: vmmetrics
          image: victoriametrics/victoria-metrics
          ports:
            - containerPort: 8428
          volumeMounts:
            - mountPath: /victoria-metrics-data
              name: vmmetrics-data
        - name: vmlogs
          image: victoriametrics/victoria-logs
          ports:
            - containerPort: 9428
          volumeMounts:
            - mountPath: /victoria-logs-data
              name: vmlogs-data

        - name: starline-api
          image: ghcr.io/ssmif-quant/starline-api
          ports:
            - containerPort: 8080
          env:
            - name: RSA_PUB_KEY
              value: "/root/keys/public.pem"
            - name: PORT
              value: "8080"
            - name: DB_NAME
              value: "ssmif_stag"
            - name: DB_USER
              value: "ssmif"
            - name: DB_PASSWORD
              value: "ztH0QCQ5yZQNCTCZNMuo"
            - name: DB_HOST
              value: "http://hanlon-clickhouse.default"
            - name: DB_PORT
              value: "18123"
            - name: OPTIMIZER_ADDR
              value: "TODO"
            - name: WEB_HOST
              value: "http://web-starline.default:3000"
          volumeMounts:
            - mountPath: /root/keys/public.pem
              name: starline-rsa-keys

      imagePullSecrets:
        - name: regcred

      volumes:
        - name: ch-data
          hostPath:
            path: /home/ec2-user/clickhouse
            type: Directory
        - name: ch-server-logs
          hostPath:
            path: /home/ec2-user/logs/clickhouse
            type: Directory
        - name: vmmetrics-data
          hostPath:
            path: /home/ec2-user/victoriametrics
            type: Directory
        - name: vmlogs-data
          hostPath:
            path: /home/ec2-user/victorialogs
            type: Directory
        - name: starline-rsa-keys
          hostPath:
            path: /home/ec2-user/.ssh/id_rsa.pub
            type: File
