apiVersion: v1
kind: Service
metadata:
  name: hanlon-clickhouse
spec:
  selector:
    app: hanlon-clickhouse
  ports:
    - name: ch
      port: 8123
      targetPort: 8123
    - name: vmetrics
      port: 8428
      targetPort: 8428
    - name: vmlogs
      port: 9428
      targetPort: 9428
