apiVersion: v1
kind: Service
metadata:
  name: hanlon-vm
  labels:
    app-logger: promtail
spec:
  selector:
    group: hanlon
  ports:
    - name: vm-metrics
      port: 8428
      targetPort: 8428
    - name: vm-logs
      port: 9428
      targetPort: 9428
