apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      group: web
  template:
    metadata:
      labels:
        group: web
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: grafana
          image: grafana/grafana-enterprise
          ports:
            - containerPort: 3001
          env:
            - name: GF_SERVER_HTTP_PORT
              value: "3001"
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-data

        - name: starline-web
          image: ghcr.io/ssmif-quant/starline-web
          env:
            - name: NEXT_PUBLIC_SERVER_URL
              value: "http://hanlon-starline.default:8080"

          ports:
            - containerPort: 3000

      imagePullSecrets:
        - name: regcred

      volumes:
        - name: grafana-data
          hostPath:
            path: /home/ec2-user/grafana
            type: Directory
